/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: '#13131b',
        'surface-dim': '#13131b',
        'surface-bright': '#393841',
        'surface-container-lowest': '#0d0d15',
        'surface-container-low': '#1b1b23',
        'surface-container': '#1f1f27',
        'surface-container-high': '#292932',
        'surface-container-highest': '#34343d',
        'on-surface': '#e4e1ed',
        'on-surface-variant': '#c7c4d7',
        'inverse-surface': '#e4e1ed',
        'inverse-on-surface': '#303038',
        outline: '#908fa0',
        'outline-variant': '#464554',
        'surface-tint': '#c0c1ff',
        primary: '#c0c1ff',
        'on-primary': '#1000a9',
        'primary-container': '#8083ff',
        'on-primary-container': '#0d0096',
        'inverse-primary': '#494bd6',
        secondary: '#4edea3',
        'on-secondary': '#003824',
        'secondary-container': '#00a572',
        'on-secondary-container': '#00311f',
        tertiary: '#ffb2b7',
        'on-tertiary': '#67001b',
        'tertiary-container': '#ff516a',
        'on-tertiary-container': '#5b0017',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary-fixed': '#07006c',
        'on-primary-fixed-variant': '#2f2ebe',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary-fixed': '#ffdadb',
        'tertiary-fixed-dim': '#ffb2b7',
        'on-tertiary-fixed': '#40000d',
        'on-tertiary-fixed-variant': '#92002a',
        background: '#13131b',
        'on-background': '#e4e1ed',
        'surface-variant': '#34343d',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['36px', { lineHeight: '44px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500', letterSpacing: '0.05em' }],
        'code-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'container-max': '1440px',
        gutter: '20px',
      },
      boxShadow: {
        'tonal-low': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        'tonal-med': '0 4px 8px 0 rgb(0 0 0 / 0.08)',
        'tonal-high': '0 12px 24px 0 rgb(0 0 0 / 0.1)',
      },
    },
  },
  plugins: [],
}