"""Initial migration

Revision ID: f17a86596071
Revises: 
Create Date: 2026-06-17 19:02:43.361418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f17a86596071'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('weighted_score', sa.Integer(), nullable=True),
    sa.Column('deploy_mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citation_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('paragraph_index', sa.Integer(), nullable=False),
    sa.Column('text_snippet', sa.Text(), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('location', sqlite.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violations')
    op.drop_table('citation_issues')
    op.drop_table('audit_records')
    # ### end Alembic commands ###
